#!/usr/bin/env zsh

() {
  # Get the current execution context and move into it
  SCRIPT_DIR=$(cd $(dirname "${(%):-%x}") && pwd)
  cd $SCRIPT_DIR || return

  # Source commons (e.g. logging)
  for libraryFile (_lib/*.zsh); do
    source $libraryFile
  done

  ensure_env

  # Use GNU Stow to unlink dotfiles
  if ! stow -D -t $HOME stow git mackup prefs zsh >/dev/null 2>&1; then
    logger "error" "Failed to unlink dotfiles!"
    exit 1
  fi
  if ! stow -D -t $HOME/.config config >/dev/null 2>&1; then
    logger "error" "Failed to unlink dotfiles!"
    exit 1
  fi

  logger "success" "Successfully unlinked dotfiles."

  sh -c 'rm "$(command -v 'starship')"'
  logger "success" "Successfully uninstalled Starship."
}
