# right_format = '$time'

[aws]
disabled = true
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = " "

[azure]
disabled = true
format = '\[[$symbol($subscription)]($style)\]'

[buf]
format = '\[[$symbol($version \(Buf $buf_version\) )]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱  $duration]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[crystal]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[deno]
format = '\[[$symbol($version)]($style)\]'

[directory]
home_symbol = "󰋜"
read_only = " 󰌾"
repo_root_format = "[$repo_root]($style)[$path]($style)[$read_only]($read_only_style) "
repo_root_style = ""
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
'Desktop' = "󰇄"
'Developer' = ""
'Documents' = "󰈙"
'Downloads' = ""
'Movies' = "󰎁"
'Music' = ""
'Pictures' = ""

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = " "

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'
symbol = " "

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
symbol = " "

[elm]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[erlang]
format = '\[[$symbol($version)]($style)\]'

[gcloud]
disabled = true
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
symbol = " "

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[haskell]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[hostname]
format = '\[[$hostname]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[julia]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\] '

[lua]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
symbol = "󰍛 "

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'
symbol = " "

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[perl]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[php]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[pulumi]
format = '\[[$symbol($username@)$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[$symbol$pyenv_prefix($version)( \($virtualenv\))]($style)\]'
symbol = " "

[red]
format = '\[[$symbol($version)]($style)\]'

[rlang]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[scala]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[singularity]
format = '\[[$symbol\($env\)]($style)\]'

[swift]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
