# TAPS

# The `brew bundle` command
tap "homebrew/bundle"
# Homebrew cask formulae for GUI apps and more
tap "homebrew/cask"
# Formulae for webfont-related tools
tap "bramstein/webfonttools"
# Formulae for version-specific AdoptOpenJDK
tap "AdoptOpenJDK/openjdk"

# BINARIES

# GNU utilities, to replace default BSD ones
brew "coreutils"
brew "findutils"
brew "grep"
brew "make"
brew "gnu-sed"

# GNU Privacy Guard, to enable GPG-signing commits
brew "gnupg"

# Get latest version of the OpenSSH utilities
brew "openssh"
brew "ssh-copy-id"

# The `wget` command
brew "wget"

# Other miscellaneous binaries
brew "ack"
brew "imagemagick"
brew "jq"
brew "mackup"    # Python
brew "mas"       # Swift
brew "mitmproxy" # Python
brew "p7zip"
brew "pigz"
brew "pkg-config"
brew "protobuf" # Python
brew "readline"
brew "sqlmap"
# brew "thefuck" # Python
brew "tree"
brew "xz"
brew "zlib"
brew "zopfli"

# General development tools
brew "gh" # Golang
brew "git"
brew "git-lfs" # Golang, Ruby
brew "hub"     # Golang
brew "nginx"
brew "shellcheck"
brew "watchman" # Python

# Database related tools
brew "postgresql"
brew "sqlite"

# Docker related tools
brew "hadolint"       # Haskell
brew "helm"           # Golang
brew "k9s"            # Golang
brew "kubernetes-cli" # Golang
brew "kustomize"      # Golang
brew "minikube"       # Golang

# Node.js related tools
brew "nvm"
brew "yarn" # Node.js

# Go related tools
brew "goenv"

# Python related tools
brew "pipx" # Python
brew "pyenv"

# Swift related tools
brew "carthage"
brew "cocoapods"

# Tools to optimise images
brew "jpegoptim"
brew "pngquant" # Rust
brew "optipng"
brew "svgo" # Node.js

# Tools to generate webfonts
brew "sfnt2woff"
brew "sfnt2woff-zopfli"
brew "woff2"

# CASKS

# Binaries and Drivers
cask "adoptopenjdk8"
cask "google-cloud-sdk"

# Browsers
cask "firefox"
cask "google-chrome"
cask "microsoft-edge"

# Utilities
cask "1password"
cask "alfred"
cask "bartender"
cask "logitech-options"
cask "mullvadvpn"
cask "notion"
cask "setapp"
cask "splashtop-business"
cask "superhuman"
cask "the-unarchiver"

# IM
cask "slack"
cask "telegram-desktop"

# Creative and Design
cask "figma"

# Development
cask "dash"
cask "docker"
cask "gpg-suite"
cask "imageoptim"
cask "iterm2"
cask "jetbrains-toolbox"
cask "ngrok"
cask "postman"
cask "visual-studio-code"

# Mobile
cask "vysor"

# MAC APPSTORE APPS

mas "Magnet", id: 441258766
mas "Speedtest by Ookla", id: 1153157709
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835

# OBSOLETE, Install From SetApp

# cask "pixelsnap"
# cask "sip"
# mas "Lungo", id: 1263070803
