[tools]
go = "1.27"
java = "zulu-17"
node = "24"
python = "3.12"
ruby = "3.4"
rust = { version = "latest", components = ["rust-analyzer", "rust-src"], targets = ["wasm32-unknown-unknown"] }

atuin = "latest"
bat = "latest"
bottom = "latest"
cloudflared = "latest"
fastfetch = "latest"
gh = "latest"
hyperfine = "latest"
jq = "latest"
mkcert = "latest"
shfmt = "latest"
tealdeer = "latest"

tokei = "latest"
uv = "latest"
xh = "latest"
yq = "latest"

"1password-cli" = "latest"
"aqua:temporalio/cli" = "latest"
starship = "latest"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
